FROM cloudslang/cloudslang

MAINTAINER FlorianJDF

RUN apt-get -y install vim emacs openssh-server git tree

WORKDIR /
RUN git clone https://github.com/mbettan/docker-containers.git /usr/cslang/cslang/content/io/cloudslang/paas/
RUN cd /usr/cslang/cslang/content/io/cloudslang/paas/ && git stash && git filter-branch --prune-empty --subdirectory-filter /cslang-heroku/content/io/cloudslang/paas/ HEAD

WORKDIR /usr/cslang/cslang/bin/

ENTRYPOINT ["sh","cslang"]
